/*
MIT License

Copyright (c) 2026 Vaclav Mach (xx0x)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include "dev/System.hpp"
#include "utils/EnumTools.hpp"
#include <cstdint>

/**
 * @brief Detects button press, hold, and multi-press events.
 * @author Vaclav Mach (xx0x)
 * @date 2026-02-02
 */
class Button
{
public:
    /**
     * @brief Lists button events generated by the state machine.
     */
    enum class Event
    {
        JUST_PRESSED,
        JUST_RELEASED,
        MEDIUM_PRESS,
        LONG_PRESS,
        MULTI_PRESS,
        COUNT
    };

    /**
     * @brief Updates button state machine and event flags.
     */
    void Update();

    /**
     * @brief Checks whether an event occurred since last Update() call.
     * @param event Event type to query.
     * @return True when the event occurred.
     */
    bool Happened(Event event);

    /**
     * @brief Indicates whether button activity should prevent sleep.
     * @return True when sleep should be postponed.
     */
    bool PreventSleep();

private:
    enum class State
    {
        IDLE,
        PRESSED,
        RELEASED,
        WAITING_FOR_MULTI
    };

    static constexpr uint32_t kMediumPressThresholdMs = 1500; // Min duration for medium press
    static constexpr uint32_t kLongPressThresholdMs = 3000;   // Min duration for long press
    static constexpr uint32_t kMultiPressWindowMs = 500;      // Max time between multi presses
    static constexpr uint8_t kMultiPressCount = 4;            // Number of presses for multi

    State state_ = State::IDLE;
    bool now_pressed_ = false;
    bool prev_pressed_ = false;
    uint32_t press_start_time_ = 0;
    uint32_t release_time_ = 0;
    uint32_t first_press_time_ = 0;

    EnumArray<Event, bool> events_{};

    bool medium_triggered_ = false;
    bool long_triggered_ = false;

    uint8_t press_count_ = 0;

    /**
     * @brief Clears one-shot event flags.
     */
    void ResetEvents();

    /**
     * @brief Resets internal button state machine.
     */
    void ResetState();
};